# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/sai/Desktop/Looping_Hardware-design/project_1/project_1.srcs/sources_1/bd/check_40G_sim/ip/check_40G_sim_uplane_packetiser_0_0/check_40G_sim_uplane_packetiser_0_0.xci
# IP: The module: 'check_40G_sim_uplane_packetiser_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sai/Desktop/Looping_Hardware-design/project_1/project_1.srcs/sources_1/bd/check_40G_sim/ip/check_40G_sim_uplane_packetiser_0_0/constraints/uplane_packetiser_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'check_40G_sim_uplane_packetiser_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/sai/Desktop/Looping_Hardware-design/project_1/project_1.srcs/sources_1/bd/check_40G_sim/ip/check_40G_sim_uplane_packetiser_0_0/check_40G_sim_uplane_packetiser_0_0.xci
# IP: The module: 'check_40G_sim_uplane_packetiser_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sai/Desktop/Looping_Hardware-design/project_1/project_1.srcs/sources_1/bd/check_40G_sim/ip/check_40G_sim_uplane_packetiser_0_0/constraints/uplane_packetiser_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'check_40G_sim_uplane_packetiser_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
