#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst_n", 1, hls_in, -1, "", "", 1),
	Port_Property("eth_data_rx_TDATA", 128, hls_in, 0, "axis", "in_data", 1),
	Port_Property("eth_data_rx_TVALID", 1, hls_in, 3, "axis", "in_vld", 1),
	Port_Property("eth_data_rx_TREADY", 1, hls_out, 3, "axis", "in_acc", 1),
	Port_Property("eth_data_rx_TUSER", 1, hls_in, 1, "axis", "in_data", 1),
	Port_Property("eth_data_rx_TKEEP", 16, hls_in, 2, "axis", "in_data", 1),
	Port_Property("eth_data_rx_TLAST", 1, hls_in, 3, "axis", "in_data", 1),
	Port_Property("cu_data_out_TDATA", 128, hls_out, 4, "axis", "out_data", 1),
	Port_Property("cu_data_out_TVALID", 1, hls_out, 7, "axis", "out_vld", 1),
	Port_Property("cu_data_out_TREADY", 1, hls_in, 4, "axis", "out_acc", 1),
	Port_Property("cu_data_out_TUSER", 1, hls_out, 5, "axis", "out_data", 1),
	Port_Property("cu_data_out_TKEEP", 16, hls_out, 6, "axis", "out_data", 1),
	Port_Property("cu_data_out_TLAST", 1, hls_out, 7, "axis", "out_data", 1),
	Port_Property("sync_data_out_TDATA", 128, hls_out, 8, "axis", "out_data", 1),
	Port_Property("sync_data_out_TVALID", 1, hls_out, 11, "axis", "out_vld", 1),
	Port_Property("sync_data_out_TREADY", 1, hls_in, 8, "axis", "out_acc", 1),
	Port_Property("sync_data_out_TUSER", 1, hls_out, 9, "axis", "out_data", 1),
	Port_Property("sync_data_out_TKEEP", 16, hls_out, 10, "axis", "out_data", 1),
	Port_Property("sync_data_out_TLAST", 1, hls_out, 11, "axis", "out_data", 1),
	Port_Property("mgmt_data_out_TDATA", 128, hls_out, 12, "axis", "out_data", 1),
	Port_Property("mgmt_data_out_TVALID", 1, hls_out, 15, "axis", "out_vld", 1),
	Port_Property("mgmt_data_out_TREADY", 1, hls_in, 12, "axis", "out_acc", 1),
	Port_Property("mgmt_data_out_TUSER", 1, hls_out, 13, "axis", "out_data", 1),
	Port_Property("mgmt_data_out_TKEEP", 16, hls_out, 14, "axis", "out_data", 1),
	Port_Property("mgmt_data_out_TLAST", 1, hls_out, 15, "axis", "out_data", 1),
	Port_Property("rx_tstamp_in_V", 80, hls_in, 16, "ap_none", "in_data", 1),
	Port_Property("rx_tstamp_out_V_V_TDATA", 80, hls_out, 17, "axis", "out_data", 1),
	Port_Property("rx_tstamp_out_V_V_TVALID", 1, hls_out, 17, "axis", "out_vld", 1),
	Port_Property("rx_tstamp_out_V_V_TREADY", 1, hls_in, 17, "axis", "out_acc", 1),
	Port_Property("ethernet_demux_state_out_V", 3, hls_out, 18, "ap_none", "out_data", 1),
};
const char* HLS_Design_Meta::dut_name = "Ethernet_demux";
