#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Feb 15 10:24:26 IST 2021
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim check_40G_sim_wrapper_behav -key {Behavioral:sim_1:Functional:check_40G_sim_wrapper} -tclbatch check_40G_sim_wrapper.tcl -protoinst "protoinst_files/bd_195b.protoinst" -protoinst "protoinst_files/check_40G_sim.protoinst" -protoinst "protoinst_files/design_1.protoinst" -view /home/ssaraswathy/Documents/ORAN_Uplane/Hardware/Ethernet/ORAN_Integration_design/project_1/check_40G_sim_wrapper_behav.wcfg -log simulate.log"
xsim check_40G_sim_wrapper_behav -key {Behavioral:sim_1:Functional:check_40G_sim_wrapper} -tclbatch check_40G_sim_wrapper.tcl -protoinst "protoinst_files/bd_195b.protoinst" -protoinst "protoinst_files/check_40G_sim.protoinst" -protoinst "protoinst_files/design_1.protoinst" -view /home/ssaraswathy/Documents/ORAN_Uplane/Hardware/Ethernet/ORAN_Integration_design/project_1/check_40G_sim_wrapper_behav.wcfg -log simulate.log

