// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "slot_Data_gen.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic slot_Data_gen::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic slot_Data_gen::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<3> slot_Data_gen::ap_ST_fsm_state1 = "1";
const sc_lv<3> slot_Data_gen::ap_ST_fsm_pp0_stage0 = "10";
const sc_lv<3> slot_Data_gen::ap_ST_fsm_state5 = "100";
const bool slot_Data_gen::ap_const_boolean_1 = true;
const sc_lv<1> slot_Data_gen::ap_const_lv1_0 = "0";
const sc_lv<1> slot_Data_gen::ap_const_lv1_1 = "1";
const sc_lv<2> slot_Data_gen::ap_const_lv2_0 = "00";
const sc_lv<2> slot_Data_gen::ap_const_lv2_2 = "10";
const sc_lv<2> slot_Data_gen::ap_const_lv2_3 = "11";
const sc_lv<2> slot_Data_gen::ap_const_lv2_1 = "1";
const sc_lv<32> slot_Data_gen::ap_const_lv32_1 = "1";
const bool slot_Data_gen::ap_const_boolean_0 = false;
const sc_lv<32> slot_Data_gen::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<16> slot_Data_gen::ap_const_lv16_0 = "0000000000000000";
const sc_lv<16> slot_Data_gen::ap_const_lv16_B328 = "1011001100101000";
const sc_lv<16> slot_Data_gen::ap_const_lv16_1 = "1";
const sc_lv<32> slot_Data_gen::ap_const_lv32_2 = "10";

slot_Data_gen::slot_Data_gen(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_01001);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_state3_io );
    sensitive << ( ap_block_state4_io );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_state3_io );
    sensitive << ( ap_block_state4_io );

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state3_io);
    sensitive << ( data_V_V_1_ack_in );
    sensitive << ( icmp_ln10_reg_80 );

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state4_io);
    sensitive << ( data_V_V_1_ack_in );
    sensitive << ( icmp_ln10_reg_80_pp0_iter1_reg );

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state5);
    sensitive << ( data_V_V_TREADY );
    sensitive << ( data_V_V_1_state );

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state2);
    sensitive << ( icmp_ln10_fu_63_p2 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_ap_phi_mux_tmp_V_phi_fu_55_p4);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( icmp_ln10_reg_80 );
    sensitive << ( tmp_V_reg_51 );
    sensitive << ( i_reg_84 );

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_data_V_V_1_ack_in);
    sensitive << ( data_V_V_1_state );

    SC_METHOD(thread_data_V_V_1_ack_out);
    sensitive << ( data_V_V_TREADY );

    SC_METHOD(thread_data_V_V_1_data_out);
    sensitive << ( data_V_V_1_payload_A );
    sensitive << ( data_V_V_1_payload_B );
    sensitive << ( data_V_V_1_sel );

    SC_METHOD(thread_data_V_V_1_load_A);
    sensitive << ( data_V_V_1_sel_wr );
    sensitive << ( data_V_V_1_state_cmp_full );

    SC_METHOD(thread_data_V_V_1_load_B);
    sensitive << ( data_V_V_1_sel_wr );
    sensitive << ( data_V_V_1_state_cmp_full );

    SC_METHOD(thread_data_V_V_1_sel);
    sensitive << ( data_V_V_1_sel_rd );

    SC_METHOD(thread_data_V_V_1_state_cmp_full);
    sensitive << ( data_V_V_1_state );

    SC_METHOD(thread_data_V_V_1_vld_in);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln10_reg_80 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_data_V_V_1_vld_out);
    sensitive << ( data_V_V_1_state );

    SC_METHOD(thread_data_V_V_TDATA);
    sensitive << ( data_V_V_1_data_out );

    SC_METHOD(thread_data_V_V_TDATA_blk_n);
    sensitive << ( data_V_V_1_state );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( icmp_ln10_reg_80 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( icmp_ln10_reg_80_pp0_iter1_reg );

    SC_METHOD(thread_data_V_V_TVALID);
    sensitive << ( data_V_V_1_state );

    SC_METHOD(thread_i_fu_69_p2);
    sensitive << ( ap_phi_mux_tmp_V_phi_fu_55_p4 );

    SC_METHOD(thread_icmp_ln10_fu_63_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_phi_mux_tmp_V_phi_fu_55_p4 );

    SC_METHOD(thread_tmp_V_1_fu_75_p1);
    sensitive << ( tmp_V_reg_51 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( data_V_V_TREADY );
    sensitive << ( data_V_V_1_state );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( icmp_ln10_fu_63_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_CS_fsm_state5 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    data_V_V_1_sel_rd = SC_LOGIC_0;
    data_V_V_1_sel_wr = SC_LOGIC_0;
    data_V_V_1_state = "00";
    ap_CS_fsm = "001";
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "slot_Data_gen_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, data_V_V_TDATA, "(port)data_V_V_TDATA");
    sc_trace(mVcdFile, data_V_V_TVALID, "(port)data_V_V_TVALID");
    sc_trace(mVcdFile, data_V_V_TREADY, "(port)data_V_V_TREADY");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, data_V_V_1_data_out, "data_V_V_1_data_out");
    sc_trace(mVcdFile, data_V_V_1_vld_in, "data_V_V_1_vld_in");
    sc_trace(mVcdFile, data_V_V_1_vld_out, "data_V_V_1_vld_out");
    sc_trace(mVcdFile, data_V_V_1_ack_in, "data_V_V_1_ack_in");
    sc_trace(mVcdFile, data_V_V_1_ack_out, "data_V_V_1_ack_out");
    sc_trace(mVcdFile, data_V_V_1_payload_A, "data_V_V_1_payload_A");
    sc_trace(mVcdFile, data_V_V_1_payload_B, "data_V_V_1_payload_B");
    sc_trace(mVcdFile, data_V_V_1_sel_rd, "data_V_V_1_sel_rd");
    sc_trace(mVcdFile, data_V_V_1_sel_wr, "data_V_V_1_sel_wr");
    sc_trace(mVcdFile, data_V_V_1_sel, "data_V_V_1_sel");
    sc_trace(mVcdFile, data_V_V_1_load_A, "data_V_V_1_load_A");
    sc_trace(mVcdFile, data_V_V_1_load_B, "data_V_V_1_load_B");
    sc_trace(mVcdFile, data_V_V_1_state, "data_V_V_1_state");
    sc_trace(mVcdFile, data_V_V_1_state_cmp_full, "data_V_V_1_state_cmp_full");
    sc_trace(mVcdFile, data_V_V_TDATA_blk_n, "data_V_V_TDATA_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, icmp_ln10_reg_80, "icmp_ln10_reg_80");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, icmp_ln10_reg_80_pp0_iter1_reg, "icmp_ln10_reg_80_pp0_iter1_reg");
    sc_trace(mVcdFile, tmp_V_reg_51, "tmp_V_reg_51");
    sc_trace(mVcdFile, icmp_ln10_fu_63_p2, "icmp_ln10_fu_63_p2");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter0, "ap_block_state2_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter1, "ap_block_state3_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state3_io, "ap_block_state3_io");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter2, "ap_block_state4_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state4_io, "ap_block_state4_io");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, i_fu_69_p2, "i_fu_69_p2");
    sc_trace(mVcdFile, i_reg_84, "i_reg_84");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, tmp_V_1_fu_75_p1, "tmp_V_1_fu_75_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state2, "ap_condition_pp0_exit_iter0_state2");
    sc_trace(mVcdFile, ap_phi_mux_tmp_V_phi_fu_55_p4, "ap_phi_mux_tmp_V_phi_fu_55_p4");
    sc_trace(mVcdFile, ap_block_pp0_stage0_01001, "ap_block_pp0_stage0_01001");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, ap_block_state5, "ap_block_state5");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
#endif

    }
    mHdltvinHandle.open("slot_Data_gen.hdltvin.dat");
    mHdltvoutHandle.open("slot_Data_gen.hdltvout.dat");
}

slot_Data_gen::~slot_Data_gen() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
}

void slot_Data_gen::thread_ap_clk_no_reset_() {
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            if (esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read())) {
                ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state2.read() ^ ap_const_logic_1);
            } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
                ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
            }
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
            ap_enable_reg_pp0_iter2 = ap_const_logic_0;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        data_V_V_1_sel_rd = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, data_V_V_1_ack_out.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, data_V_V_1_vld_out.read()))) {
            data_V_V_1_sel_rd =  (sc_logic) (~data_V_V_1_sel_rd.read());
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        data_V_V_1_sel_wr = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, data_V_V_1_vld_in.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, data_V_V_1_ack_in.read()))) {
            data_V_V_1_sel_wr =  (sc_logic) (~data_V_V_1_sel_wr.read());
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        data_V_V_1_state = ap_const_lv2_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_0, data_V_V_1_vld_in.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, data_V_V_1_ack_out.read()) && 
              esl_seteq<1,2,2>(data_V_V_1_state.read(), ap_const_lv2_3)) || 
             (esl_seteq<1,1,1>(ap_const_logic_0, data_V_V_1_vld_in.read()) && 
              esl_seteq<1,2,2>(data_V_V_1_state.read(), ap_const_lv2_2)))) {
            data_V_V_1_state = ap_const_lv2_2;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, data_V_V_1_vld_in.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_0, data_V_V_TREADY.read()) && 
                     esl_seteq<1,2,2>(data_V_V_1_state.read(), ap_const_lv2_3)) || 
                    (esl_seteq<1,1,1>(ap_const_logic_0, data_V_V_TREADY.read()) && 
                     esl_seteq<1,2,2>(data_V_V_1_state.read(), ap_const_lv2_1)))) {
            data_V_V_1_state = ap_const_lv2_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, data_V_V_1_vld_in.read()) && 
                     esl_seteq<1,2,2>(data_V_V_1_state.read(), ap_const_lv2_2)) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, data_V_V_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(data_V_V_1_state.read(), ap_const_lv2_1)) || 
                    (esl_seteq<1,2,2>(data_V_V_1_state.read(), ap_const_lv2_3) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_1, data_V_V_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_0, data_V_V_TREADY.read())) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_0, data_V_V_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_1, data_V_V_1_ack_out.read()))))) {
            data_V_V_1_state = ap_const_lv2_3;
        } else {
            data_V_V_1_state = ap_const_lv2_2;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln10_reg_80.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        tmp_V_reg_51 = i_reg_84.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        tmp_V_reg_51 = ap_const_lv16_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, data_V_V_1_load_A.read())) {
        data_V_V_1_payload_A = tmp_V_1_fu_75_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, data_V_V_1_load_B.read())) {
        data_V_V_1_payload_B = tmp_V_1_fu_75_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        i_reg_84 = i_fu_69_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        icmp_ln10_reg_80 = icmp_ln10_fu_63_p2.read();
        icmp_ln10_reg_80_pp0_iter1_reg = icmp_ln10_reg_80.read();
    }
}

void slot_Data_gen::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[1];
}

void slot_Data_gen::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void slot_Data_gen::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[2];
}

void slot_Data_gen::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void slot_Data_gen::thread_ap_block_pp0_stage0_01001() {
    ap_block_pp0_stage0_01001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void slot_Data_gen::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3_io.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state4_io.read())));
}

void slot_Data_gen::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3_io.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state4_io.read())));
}

void slot_Data_gen::thread_ap_block_state2_pp0_stage0_iter0() {
    ap_block_state2_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void slot_Data_gen::thread_ap_block_state3_io() {
    ap_block_state3_io = (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln10_reg_80.read()) && esl_seteq<1,1,1>(ap_const_logic_0, data_V_V_1_ack_in.read()));
}

void slot_Data_gen::thread_ap_block_state3_pp0_stage0_iter1() {
    ap_block_state3_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void slot_Data_gen::thread_ap_block_state4_io() {
    ap_block_state4_io = (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln10_reg_80_pp0_iter1_reg.read()) && esl_seteq<1,1,1>(ap_const_logic_0, data_V_V_1_ack_in.read()));
}

void slot_Data_gen::thread_ap_block_state4_pp0_stage0_iter2() {
    ap_block_state4_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void slot_Data_gen::thread_ap_block_state5() {
    ap_block_state5 = (esl_seteq<1,2,2>(data_V_V_1_state.read(), ap_const_lv2_1) || (esl_seteq<1,1,1>(ap_const_logic_0, data_V_V_TREADY.read()) && 
  esl_seteq<1,2,2>(data_V_V_1_state.read(), ap_const_lv2_3)));
}

void slot_Data_gen::thread_ap_condition_pp0_exit_iter0_state2() {
    if (esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln10_fu_63_p2.read())) {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_0;
    }
}

void slot_Data_gen::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void slot_Data_gen::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void slot_Data_gen::thread_ap_phi_mux_tmp_V_phi_fu_55_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln10_reg_80.read()))) {
        ap_phi_mux_tmp_V_phi_fu_55_p4 = i_reg_84.read();
    } else {
        ap_phi_mux_tmp_V_phi_fu_55_p4 = tmp_V_reg_51.read();
    }
}

void slot_Data_gen::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void slot_Data_gen::thread_data_V_V_1_ack_in() {
    data_V_V_1_ack_in = data_V_V_1_state.read()[1];
}

void slot_Data_gen::thread_data_V_V_1_ack_out() {
    data_V_V_1_ack_out = data_V_V_TREADY.read();
}

void slot_Data_gen::thread_data_V_V_1_data_out() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, data_V_V_1_sel.read())) {
        data_V_V_1_data_out = data_V_V_1_payload_B.read();
    } else {
        data_V_V_1_data_out = data_V_V_1_payload_A.read();
    }
}

void slot_Data_gen::thread_data_V_V_1_load_A() {
    data_V_V_1_load_A = (data_V_V_1_state_cmp_full.read() & ~data_V_V_1_sel_wr.read());
}

void slot_Data_gen::thread_data_V_V_1_load_B() {
    data_V_V_1_load_B = (data_V_V_1_sel_wr.read() & data_V_V_1_state_cmp_full.read());
}

void slot_Data_gen::thread_data_V_V_1_sel() {
    data_V_V_1_sel = data_V_V_1_sel_rd.read();
}

void slot_Data_gen::thread_data_V_V_1_state_cmp_full() {
    data_V_V_1_state_cmp_full =  (sc_logic) ((!data_V_V_1_state.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(data_V_V_1_state.read() != ap_const_lv2_1))[0];
}

void slot_Data_gen::thread_data_V_V_1_vld_in() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln10_reg_80.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        data_V_V_1_vld_in = ap_const_logic_1;
    } else {
        data_V_V_1_vld_in = ap_const_logic_0;
    }
}

void slot_Data_gen::thread_data_V_V_1_vld_out() {
    data_V_V_1_vld_out = data_V_V_1_state.read()[0];
}

void slot_Data_gen::thread_data_V_V_TDATA() {
    data_V_V_TDATA = data_V_V_1_data_out.read();
}

void slot_Data_gen::thread_data_V_V_TDATA_blk_n() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln10_reg_80.read())) || 
         (esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln10_reg_80_pp0_iter1_reg.read())))) {
        data_V_V_TDATA_blk_n = data_V_V_1_state.read()[1];
    } else {
        data_V_V_TDATA_blk_n = ap_const_logic_1;
    }
}

void slot_Data_gen::thread_data_V_V_TVALID() {
    data_V_V_TVALID = data_V_V_1_state.read()[0];
}

void slot_Data_gen::thread_i_fu_69_p2() {
    i_fu_69_p2 = (!ap_phi_mux_tmp_V_phi_fu_55_p4.read().is_01() || !ap_const_lv16_1.is_01())? sc_lv<16>(): (sc_biguint<16>(ap_phi_mux_tmp_V_phi_fu_55_p4.read()) + sc_biguint<16>(ap_const_lv16_1));
}

void slot_Data_gen::thread_icmp_ln10_fu_63_p2() {
    icmp_ln10_fu_63_p2 = (!ap_phi_mux_tmp_V_phi_fu_55_p4.read().is_01() || !ap_const_lv16_B328.is_01())? sc_lv<1>(): sc_lv<1>(ap_phi_mux_tmp_V_phi_fu_55_p4.read() == ap_const_lv16_B328);
}

void slot_Data_gen::thread_tmp_V_1_fu_75_p1() {
    tmp_V_1_fu_75_p1 = esl_zext<32,16>(tmp_V_reg_51.read());
}

void slot_Data_gen::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            break;
        case 2 : 
            if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln10_fu_63_p2.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln10_fu_63_p2.read()) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && !(esl_seteq<1,2,2>(data_V_V_1_state.read(), ap_const_lv2_1) || (esl_seteq<1,1,1>(ap_const_logic_0, data_V_V_TREADY.read()) && 
  esl_seteq<1,2,2>(data_V_V_1_state.read(), ap_const_lv2_3))))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        default : 
            ap_NS_fsm = "XXX";
            break;
    }
}

void slot_Data_gen::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"data_V_V_TDATA\" :  \"" << data_V_V_TDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"data_V_V_TVALID\" :  \"" << data_V_V_TVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"data_V_V_TREADY\" :  \"" << data_V_V_TREADY.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

