// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _slot_Data_gen_HH_
#define _slot_Data_gen_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct slot_Data_gen : public sc_module {
    // Port declarations 5
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst_n;
    sc_out< sc_lv<32> > data_V_V_TDATA;
    sc_out< sc_logic > data_V_V_TVALID;
    sc_in< sc_logic > data_V_V_TREADY;


    // Module declarations
    slot_Data_gen(sc_module_name name);
    SC_HAS_PROCESS(slot_Data_gen);

    ~slot_Data_gen();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    sc_signal< sc_logic > ap_rst_n_inv;
    sc_signal< sc_lv<32> > data_V_V_1_data_out;
    sc_signal< sc_logic > data_V_V_1_vld_in;
    sc_signal< sc_logic > data_V_V_1_vld_out;
    sc_signal< sc_logic > data_V_V_1_ack_in;
    sc_signal< sc_logic > data_V_V_1_ack_out;
    sc_signal< sc_lv<32> > data_V_V_1_payload_A;
    sc_signal< sc_lv<32> > data_V_V_1_payload_B;
    sc_signal< sc_logic > data_V_V_1_sel_rd;
    sc_signal< sc_logic > data_V_V_1_sel_wr;
    sc_signal< sc_logic > data_V_V_1_sel;
    sc_signal< sc_logic > data_V_V_1_load_A;
    sc_signal< sc_logic > data_V_V_1_load_B;
    sc_signal< sc_lv<2> > data_V_V_1_state;
    sc_signal< sc_logic > data_V_V_1_state_cmp_full;
    sc_signal< sc_logic > data_V_V_TDATA_blk_n;
    sc_signal< sc_lv<3> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_pp0_stage0;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter1;
    sc_signal< bool > ap_block_pp0_stage0;
    sc_signal< sc_lv<1> > icmp_ln10_reg_80;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter2;
    sc_signal< sc_lv<1> > icmp_ln10_reg_80_pp0_iter1_reg;
    sc_signal< sc_lv<16> > tmp_V_reg_51;
    sc_signal< sc_lv<1> > icmp_ln10_fu_63_p2;
    sc_signal< bool > ap_block_state2_pp0_stage0_iter0;
    sc_signal< bool > ap_block_state3_pp0_stage0_iter1;
    sc_signal< bool > ap_block_state3_io;
    sc_signal< bool > ap_block_state4_pp0_stage0_iter2;
    sc_signal< bool > ap_block_state4_io;
    sc_signal< bool > ap_block_pp0_stage0_11001;
    sc_signal< sc_lv<16> > i_fu_69_p2;
    sc_signal< sc_lv<16> > i_reg_84;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter0;
    sc_signal< sc_lv<32> > tmp_V_1_fu_75_p1;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< bool > ap_block_pp0_stage0_subdone;
    sc_signal< sc_logic > ap_condition_pp0_exit_iter0_state2;
    sc_signal< sc_lv<16> > ap_phi_mux_tmp_V_phi_fu_55_p4;
    sc_signal< bool > ap_block_pp0_stage0_01001;
    sc_signal< sc_lv<3> > ap_NS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< bool > ap_block_state5;
    sc_signal< sc_logic > ap_idle_pp0;
    sc_signal< sc_logic > ap_enable_pp0;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<3> ap_ST_fsm_state1;
    static const sc_lv<3> ap_ST_fsm_pp0_stage0;
    static const sc_lv<3> ap_ST_fsm_state5;
    static const bool ap_const_boolean_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<2> ap_const_lv2_2;
    static const sc_lv<2> ap_const_lv2_3;
    static const sc_lv<2> ap_const_lv2_1;
    static const sc_lv<32> ap_const_lv32_1;
    static const bool ap_const_boolean_0;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<16> ap_const_lv16_0;
    static const sc_lv<16> ap_const_lv16_B328;
    static const sc_lv<16> ap_const_lv16_1;
    static const sc_lv<32> ap_const_lv32_2;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_pp0_stage0();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state5();
    void thread_ap_block_pp0_stage0();
    void thread_ap_block_pp0_stage0_01001();
    void thread_ap_block_pp0_stage0_11001();
    void thread_ap_block_pp0_stage0_subdone();
    void thread_ap_block_state2_pp0_stage0_iter0();
    void thread_ap_block_state3_io();
    void thread_ap_block_state3_pp0_stage0_iter1();
    void thread_ap_block_state4_io();
    void thread_ap_block_state4_pp0_stage0_iter2();
    void thread_ap_block_state5();
    void thread_ap_condition_pp0_exit_iter0_state2();
    void thread_ap_enable_pp0();
    void thread_ap_idle_pp0();
    void thread_ap_phi_mux_tmp_V_phi_fu_55_p4();
    void thread_ap_rst_n_inv();
    void thread_data_V_V_1_ack_in();
    void thread_data_V_V_1_ack_out();
    void thread_data_V_V_1_data_out();
    void thread_data_V_V_1_load_A();
    void thread_data_V_V_1_load_B();
    void thread_data_V_V_1_sel();
    void thread_data_V_V_1_state_cmp_full();
    void thread_data_V_V_1_vld_in();
    void thread_data_V_V_1_vld_out();
    void thread_data_V_V_TDATA();
    void thread_data_V_V_TDATA_blk_n();
    void thread_data_V_V_TVALID();
    void thread_i_fu_69_p2();
    void thread_icmp_ln10_fu_63_p2();
    void thread_tmp_V_1_fu_75_p1();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
